# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: segan <segan@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/08/06 18:58:06 by segan             #+#    #+#              #
#    Updated: 2022/08/06 18:58:10 by segan            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	=	libft.a

CC		=	cc

CFLAGS	=	-Wall -Wextra -Werror

INCS	=	libft.h

AR		=	ar

RM		=	rm -f

ARFLAGS	=	-rcs

SRCS	=	ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c \
			ft_strlen.c ft_memset.c ft_bzero.c ft_memcpy.c ft_memmove.c \
			ft_strlcpy.c ft_strlcat.c ft_toupper.c ft_tolower.c ft_strchr.c \
			ft_strrchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c ft_strnstr.c \
			ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c \
			ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_striteri.c \
			ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c

SRCS_BONUS	= ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c \
			ft_lstdelone.c ft_lstclear.c ft_lstadd_back.c ft_lstiter.c \
			ft_lstmap.c

OBJS	=	$(SRCS:.c=.o)

OBJS_BONUS	=	$(SRCS_BONUS:.c=.o)

ifdef   BONUS
	SRCS += $(SRCS_BONUS)
	OBJS += $(OBJS_BONUS)
endif

all	:	$(NAME)

%.o		: %.c
		$(CC) $(CFLAGS) -c $(SRCS)

$(NAME)	:	$(OBJS)
			$(AR) $(ARFLAGS) $(NAME) $(OBJS)

bonus :
		make BONUS=1

clean :
		$(RM) $(OBJS) $(OBJS_BONUS)

fclean :
		make clean
		$(RM) $(NAME)

re :
	make fclean
	make all

.PHONY : all clean fclean re bonus
